# -*- coding: utf-8 -*-
"""USACovid19Graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kzxQuMwJ-RZyeHK4RexlHkyZUzGXkiE9
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

#### ----- Step 1 (Download data)----
URL_DATASET = r'https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv'
df1 = pd.read_csv(URL_DATASET)
# print(df1.head(3))  # Uncomment to see the dataframe

#### ----- Step 2 (Select data for India)----
df_US = df1[df1['Country'] == 'US']
print(df_US.head(10))

new_confirmed = []
def diff(i):
  global sum_of_cases
  cases = i-sum_of_cases
  sum_of_cases+=cases
  return cases

sum_of_cases = 0
df_US['New_Confirmed'] = df_US['Confirmed'].apply(diff)
sum_of_cases = 0
df_US['New_Deaths'] = df_US['Deaths'].apply(diff)
print(df_US.head(10))
print(df_US.tail(10))

#### ----- Step 3 (Plot data)----
# Increase size of plot
plt.rcParams["figure.figsize"]=20,10  # Remove if not on Jupyter
# Plot column 'Confirmed'
df_US.plot(kind = 'bar', x = 'Date', y = 'New_Confirmed', color = 'blue')

ax1 = plt.gca()
df_US.plot(kind = 'bar', x = 'Date', y = 'New_Deaths', color = 'red'
            , ax = ax1
           )
plt.show()